import Header from "@/samezone/ui/header";
import "../samezone/globals.css";
import Footer from "@/samezone/ui/footer";
import StoreProvider from "./storeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="bg-gray-400">
          <Header />
          <div className="mx-auto max-w-[1600px]">
            <main>{children}</main>
          </div>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
