import Header from "@/samezone/ui/header";
import "../samezone/globals.css";
import Footer from "@/samezone/ui/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-400">
        <Header />
        <div className="max-w-[1600px] mx-auto">
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
